# Generated by Django 2.1.3 on 2019-01-19 16:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0003_auto_20190118_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('desc', models.CharField(max_length=200, verbose_name='介绍')),
                ('click_num', models.IntegerField(default=0, verbose_name='阅读量')),
                ('favor_num', models.IntegerField(default=0, verbose_name='收藏量')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
            },
        ),
        migrations.CreateModel(
            name='AlbumCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='相册分类')),
            ],
            options={
                'verbose_name': '相册分类',
                'verbose_name_plural': '相册分类',
            },
        ),
        migrations.CreateModel(
            name='AlbumFavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('album', models.ManyToManyField(blank=True, to='index.Album', verbose_name='相册')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='AlbumTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='相册标签')),
            ],
            options={
                'verbose_name': '相册标签',
                'verbose_name_plural': '相册标签',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(blank=True, max_length=200, verbose_name='图片链接')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Album', verbose_name='相册')),
            ],
            options={
                'verbose_name': '图片链接',
                'verbose_name_plural': '图片链接',
            },
        ),
        migrations.CreateModel(
            name='SeePower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='权限')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.AlterField(
            model_name='otheruser',
            name='uuid',
            field=models.CharField(default='0837957ed6ab479d88215701d989fcaf', max_length=100, verbose_name='用户标识'),
        ),
        migrations.AddField(
            model_name='albumfavor',
            name='user',
            field=models.ManyToManyField(blank=True, to='index.OtherUser', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.AlbumCategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='album',
            name='power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.SeePower', verbose_name='权限'),
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, to='index.AlbumTag', verbose_name='标签'),
        ),
    ]
